version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
    - "8080:8080"
    hostname: frontend
    environment:
      - BACKEND_PORT=${BACKEND_PORT}

  backend:
    build: ./backend
    depends_on:
      - mongodb
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - JWT_TOKEN_SECRET_KEY=${JWT_TOKEN_SECRET_KEY}
      - JWT_TOKEN_EXPIRY=${JWT_TOKEN_EXPIRY}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

  mongodb:
    image: mongo:3.6.21
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./initdb.sh/:/docker-entrypoint-initdb.d/init.sh:ro
