version: "3.8"
services:
    frontend:
      build: ./frontend
      ports:
        - "8080:8080"
      depends_on:
        - backend
      environment:
        - BACKEND_URL=127.0.0.1:${BACKEND_PORT}
        - FRONTEND_PORT=${FRONTEND_PORT}

    backend:
      build: ./backend
      depends_on:
        - mongo
      ports:
        - "3000:3000"
      environment:
        - BACKEND_PORT=${BACKEND_PORT}
        - BACKEND_ENCRYPTION_KEY=${BACKEND_ENCRYPTION_KEY}
        - JWT_TOKEN_SECRET_KEY=${JWT_TOKEN_SECRET_KEY}
        - JWT_TOKEN_EXPIRY=${JWT_TOKEN_EXPIRY}
        - MONGO_HOST=mongo
        - MONGO_DATABASE=${MONGO_DATABASE}
        - MONGO_USERNAME=${MONGO_USERNAME}
        - MONGO_PASSWORD=${MONGO_PASSWORD}

  mongo:
    image: mongo:3.6.21
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./initdb.sh/:/docker-entrypoint-initdb.d/init.sh:ro
